version: "3.5"

services:
  frontend:
    image: docker.ub.gu.se/grupprum:${GIT_REVISION}
    ports:
      # Port differs in release image for ember
      # TODO: Change so nginx listens at 4200 instead to we don't need this?
      - 4200:8080
  backend:
    image: docker.ub.gu.se/grupprum-server:${GIT_REVISION}
  db:
    image: docker.ub.gu.se/grupprum-postgres:${GIT_REVISION}