version: "3.5"
services:
    db:
        restart: always
        environment:
            - POSTGRES_DB=${DB}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./postgres-initdb.d:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data
    backend:
        restart: always
        depends_on:
            - db
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=5432
            - DB=${DB}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SECRET_KEY_BASE=${SECRET_KEY_BASE}
            - AUTH_URL=${AUTH_URL}
        ports:
            - ${RAILS_SERVICE_PORT}:3000

    frontend:
        # Keep the stdin open, so we can attach to our app container's process
        # and do things such as debugging, etc
        stdin_open: true
        tty: true
        environment:
            - EMBER_ENVIRONMENT=${ENVIRONMENT}
            - SERVICE_HOSTNAME=${SERVICE_HOSTNAME}
            - BACKEND_SERVICE_PORT=${RAILS_SERVICE_PORT}
volumes:
    dbdata: